### ISSUE TITLE
 open store front http://localhost:2083/en-US/ with vue-starter-theme ,it return errors

### ISSUE THREAD

**Issue by six006** [VirtoCommerce/vc-module-experience-api#286]
when open store front http://localhost:2083/en-US/ with vue-starter-theme ,it return errors , some steps can see from here.
![image](https://user-images.githubusercontent.com/5348170/156385858-fa04923f-601c-4c19-8725-8b9f61f3ee94.png)

![image](https://user-images.githubusercontent.com/5348170/156385997-52de4eae-34c9-436b-bc0b-177803e57f7a.png)

![image](https://user-images.githubusercontent.com/5348170/156386074-8fe0d361-935d-4eb2-a81a-d67d42e1178c.png)

```
{"errors":[{"message":"GraphQL.Validation.Errors.FieldsOnCorrectTypeError: Cannot query field 'me' on type 'Query'.","locations":[{"line":2,"column":3}],"extensions":{"code":"FIELDS_ON_CORRECT_TYPE","codes":["FIELDS_ON_CORRECT_TYPE"],"number":"5.3.1"}}]}
```

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-7958 has been created

**Comment by DanilBayushev** [comment]
This error means you haven’t Profile support in the XAPI layer.

To fix this error the [VirtoCommerce.ProfileExperienceApiModule](https://github.com/VirtoCommerce/vc-module-profile-experience-api) module with version at least 3.201 is required.

**Comment by six006** [comment]
thanks @DanilBayushev

**Comment by six006** [comment]
thanks @DanilBayushev.

**Comment by six006** [comment]
thanks @DanilBayushev.
