### ISSUE TITLE
Cart Line Item has unavailable fulfillment center

### ISSUE THREAD

**Issue by Grosam** [VirtoCommerce/vc-module-experience-api#428]
Module version: 3.301.6

Let's consider the next configuration:
There is a store without main fulfillment center and with one additional fulfillment center called FC1 which has 10 items of SKU1.
Also there is fulfillment center FC2 with 20 items of SKU1. FC2 is not linked to the store.

When SKU1 is added to cart by user of the store with FC1, corresponding cart line item in the DB has fulfillment center FC2, not FC1. That leads to saving wrong fulfillment center in Order Line Item as well.

Probably this bug can be fixed by modifiying `VirtoCommerce.XDigitalCatalog.ExpProduct.ApplyStoreInventories`

Currently it looks like this:
```
            AllInventories.Clear();
            Inventory = null;
            AllInventories = inventories.Where(x => x.ProductId == Id && availFullfilmentCentersIds.Contains(x.FulfillmentCenterId)).ToList();

            Inventory = inventories.OrderByDescending(x => Math.Max(0, x.InStockQuantity - x.ReservedQuantity)).FirstOrDefault();
```

We need to change the line with setting `Inventory` property to search in `AllInventories` instead of `inventories` as `inventories` variable has inventofies from all fulfillment centers.
```
            AllInventories.Clear();
            Inventory = null;
            AllInventories = inventories.Where(x => x.ProductId == Id && availFullfilmentCentersIds.Contains(x.FulfillmentCenterId)).ToList();

            Inventory = AllInventories.OrderByDescending(x => Math.Max(0, x.InStockQuantity - x.ReservedQuantity)).FirstOrDefault();
```

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8420 has been created

**Comment by Dan-BV** [comment]
Hi, @Grosam !
We thank you for your appeal. A bug has been added to the platform project on this issue. We will inform you about the change in its status.

**Comment by Dan-BV** [comment]
Resolved by the Platform Team.
Release: https://github.com/VirtoCommerce/vc-module-experience-api/releases/tag/3.410.0
