### ISSUE TITLE
Error while getting wishlist with product prices

### ISSUE THREAD

**Issue by Grosam** [VirtoCommerce/vc-module-experience-api#436]
Getting a wishlist by id with product prices sometimes results in the following exception.

![image_2023-07-13_16-20-19](https://github.com/VirtoCommerce/vc-module-experience-api/assets/129979812/a1d13ad4-36ea-453b-8aab-7dd12396fdd8)

It seems that the exception is thrown when a product in the wishlist does not have any price. It can be fixed by adding  [this line](https://github.com/VirtoCommerce/vc-module-experience-api/blob/a9505bda20f0d2b7295d2a1620191e61ea0a4faf/src/XPurchase/VirtoCommerce.XPurchase/Schemas/PurchaseSchema.cs#L89C84-L89C84) and setting request currency with the following extension method:
`VirtoCommerce.ExperienceApiModule.Core.Extensions.ResolveFieldContextExtensions.SetCurrency`

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8415 has been created

**Comment by Dan-BV** [comment]
Hi, @Grosam!
The platform team has issued a release with a fix for this issue.
Release: https://github.com/VirtoCommerce/vc-module-experience-api/releases/tag/3.301.18
