### ISSUE TITLE
order search issue using orders query having issue with subscription 

### ISSUE THREAD

**Issue by Koshalgarg155** [VirtoCommerce/vc-module-experience-api#442]
Hi,
I am using Experience module version 3.236.0. In this module, i am calling graphql query orders. that query is returning me subscriptions and orders both. But I want that query not to return subscriptions i just want to orders in the query. So How can i handle that?

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8430 has been created

**Comment by AlexTzykin** [comment]
@Koshalgarg155 Hi! Your subscriptions have a search index?any custom modules?
Could you send an example request and response?

**Comment by Koshalgarg155** [comment]
@AlexTzykin 
i have enabled search index for orders only i don't know why its indexing subscriptions

**Comment by Koshalgarg155** [comment]
without custom module also its indexing subscriptions and searching that orders

**Comment by AlexTzykin** [comment]
@Koshalgarg155 Yes, thank you. The problem has come to light. We will take the issue to work as soon as possible.

**Comment by Koshalgarg155** [comment]
Ok @AlexTzykin

**Comment by OlegoO** [comment]
@Koshalgarg155 The reason for the error: Order module indexes order templates that are used by Subscriptions module. To fix it, we added IsPrototype to the index document. To exclude order templates from response after the update, you can use "IsPrototype: false". 

https://github.com/VirtoCommerce/vc-module-order/pull/376

**Comment by Koshalgarg155** [comment]
Hi @OlegoO 
we are using platform version: 3.253.1 and order module version : 3.214.0

**Comment by Dan-BV** [comment]
Hi, @Koshalgarg155 !
The platform team has issued a release with a fix for this issue.

**Releases:**

https://github.com/VirtoCommerce/vc-module-order/releases/tag/3.216.13  - Only Bug fix without update in Filter dialog

https://github.com/VirtoCommerce/vc-module-order/releases/tag/3.225.14 

https://github.com/VirtoCommerce/vc-module-order/releases/tag/3.410.0

**Comment by Koshalgarg155** [comment]
Hi @Dan-BV @OlegoO ,
I am using 3.216.14. I think it should be the same as 3.216.13. It's not working. do i have to turn on or of anything in that order module version?

**Comment by Koshalgarg155** [comment]
@Dan-BV @OlegoO 
Please check this version

**Comment by OlegoO** [comment]
@Koshalgarg155 Did you rebuild index for order documents after update? 

If you still see the issue, could you share 1. your grapql query and response; 2. Index document for order template.

**Comment by Koshalgarg155** [comment]
ok @OlegoO  i am checking and sending here

**Comment by Koshalgarg155** [comment]
I am sending for 3.216.14 I have installed 3.216.14 because 3.216.13 shows that the build does not exist.

**Comment by Koshalgarg155** [comment]
@OlegoO 
from where i can get Index document for order template.

**Comment by Koshalgarg155** [comment]
i have 874 orders in platform and in index its showing index documents 945
![image](https://github.com/VirtoCommerce/vc-module-experience-api/assets/99241542/1d11ed2e-006d-4157-af78-7d53234a0f55)
![image](https://github.com/VirtoCommerce/vc-module-experience-api/assets/99241542/ca0124d2-a62b-4fec-97b1-b1464ef6a962)

**Comment by Koshalgarg155** [comment]
```query orders($userId: String!, $first: Int!, $after: String!, $sort: String!, $filter: String!) {
  nbOrders(
    userId: $userId
    first: $first
    after: $after
    sort: $sort
    filter: $filter
  ) {
    totalCount
    items {
      coupons
      modifiedBy
      number
      status
      createdDate
      total {
        formattedAmount
      }
      addresses {
        id
        name
        firstName
        lastName
        addressType
        line1
        line2
        regionId
        city
        regionName
        postalCode
        countryName
        phone
      }
      inPayments {
        billingAddress {
          id
          name
          firstName
          lastName
          addressType
          line1
          line2
          regionId
          city
          regionName
          postalCode
          countryName
        }
      }
      dynamicProperties {
        name
        value
      }
      Items {
        name
        quantity
        productId
        price {
          formattedAmount
        }
        product {
          slug
          properties {
            name
            value
          }
        }
      }
      discounts {
        coupon
      }
      taxTotal {
        formattedAmount
      }
      discountTotal {
        formattedAmount
      }
      subTotal {
        formattedAmount
      }
      shippingTotal {
        formattedAmount
      }
    }
  }
}

**Comment by Koshalgarg155** [comment]
Hi @OlegoO @Dan-BV 
please check above comments

**Comment by Koshalgarg155** [comment]
Hi @Dan-BV 
have you checked above comments ?
