### ISSUE TITLE
Enhasment: Filtration of available product inventory

### ISSUE THREAD

**Issue by Grosam** [VirtoCommerce/vc-module-experience-api#444]
There is a need to apply inventories to products based on fulfillment center type (a field that we have added to fulfillment centers in our extension module) so we would like to have a way to influence the logic of applying product inventories in `VirtoCommerce.XDigitalCatalog.Middlewares.EvalProductsInventoryMiddleware`. It would be nice if there was a virtual method for configuring the search criteria or a call to `GenericPipelineLauncher` like it is done in `VirtoCommerce.XDigitalCatalog.Middlewares.EvalProductsPricesMiddleware` with passing `PriceEvaluationContext` to it.

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8435 has been created

**Comment by OlegoO** [comment]
Created PR https://github.com/VirtoCommerce/vc-module-experience-api/pull/522

**Comment by OlegoO** [comment]
Fixed in https://github.com/VirtoCommerce/vc-module-experience-api/releases/tag/3.803.0
