### ISSUE TITLE
Unable to fetch catalog products

### ISSUE THREAD

**Issue by jewells77** [VirtoCommerce/vc-module-experience-api#450]
I'm using platform version "3.306.0". vc-module-experience-api version: "3.320.0". On my local platform, I have connected with elastic search. Category queries work fine, but I'm facing issues with search product queries. There is no error, but it is still not returning data.

```
query SearchProducts($storeId: String!, $userId: String!, $currencyCode: String!, $cultureName: String, $filter: String, $after: String, $first: Int, $sort: String, $query: String, $fuzzy: Boolean, $fuzzyLevel: Int, $productIds: [String], $withFacets: Boolean!, $withImages: Boolean!) {
  products(
    storeId: $storeId
    userId: $userId
    after: $after
    first: $first
    filter: $filter
    sort: $sort
    currencyCode: $currencyCode
    cultureName: $cultureName
    query: $query
    fuzzy: $fuzzy
    fuzzyLevel: $fuzzyLevel
    productIds: $productIds
  ) {
    totalCount
    items {
      name
      id
      code
      minQuantity
      maxQuantity
      hasVariations
      slug
      outline
      imgSrc
      images @include(if: $withImages) {
        url
      }
      description(type: "QuickReview") {
        content
        id
      }
      availabilityData {
        isActive
        isAvailable
        isBuyable
        isInStock
        availableQuantity
      }
      price {
        actual {
          amount
          formattedAmount
        }
        discountAmount {
          amount
          formattedAmount
        }
        sale {
          amount
          formattedAmount
        }
        list {
          amount
          formattedAmount
        }
        discountPercent
      }
      properties {
        name
        value
        id
      }
    }
    term_facets @include(if: $withFacets) {
      name
      label
      terms {
        label
        term
        count
        isSelected
      }
    }
    range_facets @include(if: $withFacets) {
      name
      label
      ranges {
        label
        count
        from
        to
        includeFrom
        includeTo
        isSelected
      }
    }
  }
}

```
variables are
```
{
  "storeId": "B2B-Store",
  "userId": "c870ce66-ec08-4974-8cd5-b93d254822da",
  "cultureName": "en-AU",
  "currencyCode": "AUD",
  "sort": "",
  "withFacets": true,
  "withImages": true,
  "query": "",
  "filter": "category.subtree:c75392dc-3006-4688-bdd9-7c1853fa3acb",
  "first": 16,
  "after": "0"
}
```

**Comment by mvktsk** [comment]
Task https://virtocommerce.atlassian.net/browse/VP-8444 has been created

**Comment by Dan-BV** [comment]
Hi, @jewells77 !
Are we correct that the response to the query looks like the one shown below?

```
{
  "data": {
    "products": {
      "totalCount": 0,
      "items": [],
      "term_facets": [],
      "range_facets": []
    }
  }
}
```

We have used the query you attached on our environments, changing only the user ID and the directory ID. Everything works correctly.
Could you please confirm that the catalog for which you configured the filter has products and they are indexed?

We would be grateful if you could provide any clarifying information - it will help us to understand the problem faster.

**Comment by jewells77** [comment]
> Hi, @jewells77 ! Are we correct that the response to the query looks like the one shown below?
> 
> ```
> {
>   "data": {
>     "products": {
>       "totalCount": 0,
>       "items": [],
>       "term_facets": [],
>       "range_facets": []
>     }
>   }
> }
> ```
> 
> We have used the query you attached on our environments, changing only the user ID and the directory ID. Everything works correctly. Could you please confirm that the catalog for which you configured the filter has products and they are indexed?
> 
> We would be grateful if you could provide any clarifying information - it will help us to understand the problem faster.

Yes, the response looks that way. We are using the local platform with an elastic search setup. Catalog, categories, and products are indexed, but it's still the same after changing the user id, catalog id, and store id. I'm using dummy data that the platform automatically imports.

**Comment by Dan-BV** [comment]
Please provide the **vc-package.json** file of the platform you have installed.

![image](https://github.com/VirtoCommerce/vc-module-experience-api/assets/110034308/dc1d1845-04ef-4026-8efe-56bd519f824f)

**Comment by Koshalgarg155** [comment]
[vc-package.zip](https://github.com/VirtoCommerce/vc-module-experience-api/files/12682294/vc-package.zip)

**Comment by Koshalgarg155** [comment]
Hi @Dan-BV 
here is package file json for the platform

**Comment by jewells77** [comment]
> Hi @Koshalgarg155 ! We have pulled up the platform and modules version from the manifest you attached, but it was still not possible to reproduce the issue.
> 
> ![image](https://user-images.githubusercontent.com/110034308/271920503-25589b99-d2dd-498d-abfd-a5cf36adda86.png)
> 
> Could you please send us an image of the **B2B-Store** configuration, as well as the index document of one of the catalog products **c75392dc-3006-4688-bdd9-7c1853fa3acb** from your request? Sample images below.
> 
> ![image](https://user-images.githubusercontent.com/110034308/271919178-3566e2da-6726-4b14-90c0-aa03a935324d.png)
> 
> ![image](https://user-images.githubusercontent.com/110034308/271920177-3e7f4232-0cb8-4719-b96f-212d89076848.png)

We have fixed it by upgrading the version 
![image](https://github.com/VirtoCommerce/vc-module-experience-api/assets/79835068/c6757325-a30e-47ce-aeac-a34cbf751cde)
